<?php
define('_main_lang',"fa");
define('_css','-fa');

define('_tags','تگ ها');
define('_questions','سوالات');
define('_home','خانه');
define('_questions2','سوالات');
define('_users','کاربران');
define('_users2','کاربران');
define('_search','جست و جو...');
define('_profile','پروفایل');
define('_login','ورود');
define('_logout','خروج');
define('_sign_up','ثبت نام');
define('_language','انتخاب زبان');
define('_english','انگلیسی');
define('_persian','فارسی');

define('_answers','جواب ها');
define('_votes','رای ها');
define('_views','بازدیدها');

define('_email_not_registered', "ورود ناموفق است. لطفاً صحت ایمیل خود را بررسی نمایید");
define('_invalid_password', "رمز عبور شما اشتباه است");
define('_already_registered', "شما پیشتر ثبت نام کرده اید، کافیست وارد سایت شوید");
define('_weak_password', "پسورد به اندازه کافی قوی نمی باشد");
define('_password_not_match', "پسورد ها با هم مطابقت ندارند");

define('_e_Illegal_character', "کاراکتر غیرمجاز");
define('_e_name_notempty', "نام نمیتواند خالی باشد");
define('_e_name_small', "نام حداقل باید 5 حرف داشته باشد");
define('_e_name_inuse', "این نام قبلا استفده شده است، لطفا نام دیگری وارد نمایید");
define('_e_email_notempty', "ایمیل نمیتواند خالی باشد");
define('_e_email_inuse', "این ایمیل قبلا استفاده شده است، لطفا ایمیل دیگری وارد نمایید");
define('_e_pass_small', "رمز عبور حداقل باید 5 حرف داشته باشد");
define('_e_pass_notempty', "رمز عبور نمیتواند خالی باشد");

define('_in_email', "ایمیل متبر نیست");
define('_header_welcome', "خوش آمدید");

define('_btn_register', "ثبت");
define('_btn_login', "ورود");
define('_btn_post_question', "سوال خود را بنویسید");
define('_btn_signup', "ثبت نام");

define('_ph_email', "ایمیل");
define('_ph_password', "رمزعبور");
define('_ph_confirm_password', "تایید رمزعبور");
define('_ph_username', "نام کاربری");
define('_ph_nickname', "نام مستعار");

define('_tagged_questions','سوالات تگ شده');
define('_all_questions','تمامی سوالات');
define('_top_questions', "برترین سوالات");
define('_interesting', "جالب");
define('_recent','جدید');
define('_online', "آنلاین");
define('_offline', "آفلاین");
define('_comments', "نظرات");
define('_delete', "حذف");
define('_add_Comment', "اضافه کردن نظر");
define('_submit', "تایید");
define('_title', "عنوان");
define('_Liked_Post', " پست شما را پسندیده است در");
define('_ask_a_question', "سوال خود را بپرسید");
define('_content_notfound', "متاسفم، محتوای مورد نظر وجود ندارد");

define('_user_name_is', "نام کاربری: ");
define('_member_title_is', "عنوان کاربر: ");
define('_register_time_is', "تاریخ ثبت: ");
define('_last_activity_is', "آخرین فعالیت: ");
define('_total_online_time_is', "کل زمان آنلاین بودن: ");
define('_activity_is ', "فعالیت: ");

define('_search_results','نتایج جست و جو');
define('_users_list','لیست کاربران');
define('_nothing_yet','این کاربر فعلا چیزی درمورد خود ننوشته!');
define('_This_Users_Favourite_Tags','تگهای مورد علاقه ی این کاربر');
define('_Your_Favourite_Tags','تگهای مورد علاقه ی شما');
define('_No_favourite_tags_yet','تگ مورد علاقه ای فعلا وجودندارد');
define('_add_ftag','افزودن');
define('_Questions_You_Asked','سوالاتی که شما پرسیده اید');
define('_Questions_Asked_By_This_User','سوالاتی که توسط این کاربر پرسیده شده است');
define('_Questions_You_Have_Answered','سوالاتی که شما جواب داده اید');
define('_Questions_Answered_By_This_User','سوالاتی که این کاربر جواب داده است');
define('_answers2','جواب');
define('_edit','ویرایش');
define('_edit_about','ویرایش درباره خود');
define('_save','ذخیره');
define('_upload','بارگذاری');
define('_reputation','اعتبار');
define('_asked','پرسیده شد در ');
define('_edited','ویرایش شد در ');
define('_view_changes','مشاهده تغییرات');
define('_answered','پاسخ داده شد در ');
define('_modified','ویرایش شده در ');
define('_view_comments','مشاهده نظرات');
define('_comment','نظر دادن');
define('_Post_Your_Answer','ارسال پاسخ شما');
define('_post','ارسال');
define('_save_changes','ذخیره تغییرات');
define('_question_will_not','اگر فیلد عنوان و متن خالی باشد،سوال شما ثبت نخواهد شد.');
define('_how_to_ask','چگونه بپرسیم');
define('_is_your_question','آیا سوال شما درمورد برنام نویسی است؟');
define('_we_prefer','ماسوالاتی را ترجیح می دهیم که بتوان به آن ها جواب داد،نه فقط درموردشان بحث کرد.');
define('_provide_share','جزییات را بیان کنید،تحقیقات خود را با اشتراک بگذارید.');
define('_how_to_format','چگونه بنویسیم');
define('_put_return','◄بین پاراگراف ها فاصله بگذارید.');
define('_italic','◄italic یا bold');
define('_make_link','◄برای ساختن لینک از لینکساز ویرایشگر متن استفاده کنید.');
define('_how_to_tag','چگونه تگ بنویسیم');
define('_a_tag_is','تگ یک کلیدواژه یا برچسب است که سوال شما را با سایر سوالات دسته بندی می کند.');
define('_favor_tag','◄از تگ های رایج استفاده کنید،از ایجاد تگ جدید بپرهیزید.');
define('_abbreviations','◄از اختصارات رایج استفاده کنید.');
define('_syno','◄از مترادفات استفاده نکنید.');
define('_combine','◄کلمات چند بخشی را با استفاده از خط تیره به یک کلمه تبدیل کنید.');
define('_max_tag','◄حداکثر پنج تگ و طول هر تگ بیست کاراکتر');
define('_tag_char','◄کاراکترهای تگ:[a-z 0-9 + # - .]');
define('_delimit_tag','◄تگ ها را با استفاده از کاما(،)از هم جداکنید،درغیر این صورت تگ های سوال شما ثبت نخواهند شد.');
define('_Post_Your_Question','ارسال سوال شما');
define('_just_now','همین الان');
define('_yesterday',' دیروز');
define('_ago','قبل ');
define('_voted_up','پست شمارا پسندید');
define('_voted_down','پست شمارا نپسندید');
define('_on','در');
define('_achievements','دستاوردها');
define('_chat','چت');
define('_cancel','انصراف');
define('_profile_views','بازدید پروفایل: ');
define('_total_answers','تعداد پاسخ ها: ');
define('_total_q','تعداد سوالات پرسیده شده: ');
define('_favourite_tags','تگ های موردعلاقه: ');
define('_member_since','عضو از: ');
define('_revision','تجدید نظرات');
define('_group','گروه: ');
define('_administration','مدیریت');
?>