<?php
define('_main_lang',"en");
define('_css','');

define('_tags','Tags');
define('_questions','Questions');
define('_home','home');
define('_questions2','questions');
define('_users','Users');
define('_users2','users');
define('_search','Search...');
define('_profile','Profile');
define('_login','Log In');
define('_logout','Log Out');
define('_sign_up','Sign Up');
define('_language','Language');
define('_english','English');
define('_persian','Persian');

define('_answers','answers');
define('_votes','votes');
define('_views','views');

define('_email_not_registered', "Login failed, check your email or create new account");
define('_invalid_password', "Password didn't match");
define('_already_registered', "You're already registered");
define('_weak_password', "Passwords aren't strong enought");
define('_password_not_match', "Passwords not matched");

define('_e_Illegal_character', "Illegal character");
define('_e_name_notempty', "Display name can not be empty");
define('_e_name_small', "Display name must contain more that 5 letters");
define('_e_name_inuse', "This name is being used,please choose another one");
define('_e_email_notempty', "Email can not be empty");
define('_e_email_inuse', "This email is being used,please choose another one");
define('_e_pass_small', "Password must contain more that 5 letters");
define('_e_pass_notempty', "Password can not be empty");

define('_in_email', "Invalid Email");
define('_header_welcome', "welcome");

define('_btn_register', "Register");
define('_btn_login', "Login");
define('_btn_post_question', "Post Your Question");
define('_btn_signup', "Sign Up");

define('_ph_email', "Email");
define('_ph_password', "Password");
define('_ph_confirm_password', "Confirm Password");
define('_ph_username', "username");
define('_ph_nickname', "Nickname");

define('_tagged_questions','Tagged Questions');
define('_all_questions','All Questions');
define('_top_questions', "Top Questions");
define('_interesting', "interesting");
define('_recent','recent');
define('_online', "ONLINE");
define('_offline', "OFFLINE");
define('_comments', "Comments");
define('_delete', "delete");
define('_add_Comment', "Add Comment");
define('_submit', "Submit");
define('_title', "Title");
define('_Liked_Post', " Liked Your Post on");
define('_ask_a_question', "Ask a question");
define('_content_notfound', "Sorry we could not find the content You were looking for");

define('_user_name_is', "User name: ");
define('_member_title_is', "Member title: ");
define('_register_time_is', "Register time: ");
define('_last_activity_is', "Last activity: ");
define('_total_online_time_is', "total online time: ");
define('_activity_is ', "Activity: ");

define('_search_results','Search Results');
define('_users_list','users list');
define('_nothing_yet','This user has not written anything about him/her self yet!');
define('_This_Users_Favourite_Tags','This Users Favourite Tags');
define('_Your_Favourite_Tags','Your Favourite Tags');
define('_No_favourite_tags_yet','No favourite tag yet!');
define('_add_ftag','add');
define('_Questions_You_Asked','Questions You Asked');
define('_Questions_Asked_By_This_User','Questions Asked By This User');
define('_Questions_You_Have_Answered','Questions You Have Answered');
define('_Questions_Answered_By_This_User','Questions Answered By This User');
define('_answers2','Answer(s)');
define('_edit','edit');
define('_edit_about','edit about yourself');
define('_save','save');
define('_upload','upload');
define('_reputation','reputation');
define('_asked','asked ');
define('_edited','edited ');
define('_view_changes','view changes');
define('_answered','answered ');
define('_modified','modified ');
define('_view_comments','view comments');
define('_comment','comment');
define('_Post_Your_Answer','Post Your Answer');
define('_post','Post');
define('_save_changes','Save Changes');
define('_question_will_not','Your question will not be stored unless you fill title and body fields.');
define('_how_to_ask','How to Ask');
define('_is_your_question','Is your question about programming?');
define('_we_prefer','We prefer questions that can be answered, not just discussed.');
define('_provide_share','Provide details. Share your research.');
define('_how_to_format','How to format');
define('_put_return','► put returns between paragraphs');
define('_italic','►italic or bold');
define('_make_link','► to make links,use editor\'s insert link option.');
define('_how_to_tag','How to Tag');
define('_a_tag_is','A tag is a keyword or label that categorizes your question with other, similar questions.');
define('_favor_tag','► favor existing popular tags; avoid creating new tags');
define('_abbreviations','► use common abbreviations');
define('_syno','► do not include synonyms');
define('_combine','► combine multiple words into single-words with dashes');
define('_max_tag','► maximum of 5 tags, 25 chars per tag');
define('_tag_char','► tag characters: [a-z 0-9 + # - .]');
define('_delimit_tag','► delimit tags by comma,your questions tags will not be stored if there be no comma.');
define('_Post_Your_Question','Post Your Question');
define('_just_now','just now');
define('_yesterday',' Yesterday');
define('_ago',' ago');
define('_voted_up','voted your post up');
define('_voted_down','voted your post down');
define('_on','on');
define('_achievements','ACHIEVEMENTS');
define('_chat','Chat');
define('_cancel','cancel');
define('_profile_views','Profile Views: ');
define('_total_answers','Total Answers: ');
define('_total_q','Questions Asked: ');
define('_favourite_tags','Favourite Tags: ');
define('_member_since','Member Since: ');
define('_revision','revisions');
define('_group','Group: ');
define('_administration','Administration');
?>